### ISSUE TITLE
Upgrade example to Vaadin 14+

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/JavascriptFlowTutorial#1]
This example is based on Vaadin 12. Upgrading to Vaadin 14 requires either enabling bower compatibility mode or replacing webjars imports with npm imports.

https://github.com/FlowingCode/JavascriptFlowTutorial/blob/f99d42d3bca7f184b3f2887c9908732a9c5a794d/src/main/java/com/flowingcode/Timeline.java#L17-L18

**Comment by mlopezFC** [comment]
The best way would be to use npm imports but I tried and I couldn't make it work (I couldn't even find the exact version that we're using on the tutorial on npmjs). So I thought that given that these are regular JavaScript libraries, and not JavaScript modules, it is just a matter of changing the JavaScript annotation and replace it with `UI.getCurrent().getPage().addJavaScript()`
I tried that approach and now it is working, so I pushed [a new branch](https://github.com/FlowingCode/JavascriptFlowTutorial/tree/v14) with this solution so the sample it is still working.
